# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & test

on:
  push:
    branches-ignore: [ "main" ]
    tags-ignore: 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

    - name: Run govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...
